########################################################################################
# 			Config file for SNPannotator package
# Please do not change section titles or variable names.
# Variables can be uncommented by deleting the semicolon at the beginning of the line.
# Default values will be used for commented variables.
########################################################################################

[general]

# where to save reports, active directory will be used by default
;outputFolder = .

# the name that will be used for saving output files
projectName = thisProject

# The list of variants to be looked up. Each rsID should be provided on a separate line in the input file.
inputFile = input.txt

# The population that should be used for LD calculation based on Ensembl data.
# The list is available from Ensembl website and also from `EnsemblDatabases()` function.
# Some of the more popular databases are mentioned as examples:
#1000GENOMES:phase_3:ALL
#1000GENOMES:phase_3:EUR
#1000GENOMES:phase_3:AFR
#1000GENOMES:phase_3:AMR
#1000GENOMES:phase_3:YRI
db = 1000GENOMES:phase_3:EUR

# Number of base pairs around the variant for checking LD scores (accepted range: 100–500 kb, inclusive). Only mention the numeric part please without kb infront.
window_size=500

# The LD threshold for selecting variants around the target SNP.
# Lower threshold could result in so many variants and significantly longer running-time.
r2=0.8

# If set to TRUE, variants in high LD will be found and added to the output.
LDlist = TRUE

# type of nearest gene to return, e.g. "all" , "protein_coding"
# "all" will return whichever gene was nearest
nearestGene_type = all

# whether to save an html report
generateHTML = TRUE


[API]

ENSEMBL_API_ENDPOINT = https://rest.ensembl.org

# Other version of data can be selected using below URLs.
# Information about the possible endpoint URLs are available from: https://ensembl.org/Help/ArchiveList
# 115 ==> https://rest.ensembl.org ### the current release for GRCH38
# 115 ==> https://grch37.rest.ensembl.org ### the latest release for GRCH37
# 114 ==> https://may2025.rest.archive.ensembl.org ## previous release of GRCH37
# 113 ==> https://oct2024.rest.archive.ensembl.org
# 112 ==> https://may2024.rest.archive.ensembl.org


EBI_API_ENDPOINT = https://www.ebi.ac.uk/eqtl/api/v3
# This is the latest available API from eQTL catalogue: https://www.ebi.ac.uk/eqtl/api/docs

GTEX_API_ENDPOINT = https://gtexportal.org/api/v2
# This is the latest available API from GTEx: https://gtexportal.org/home/apiPage

STRING_API_ENDPOINT = https://version-11-0.string-db.org/api
# previous version of data can be selected using below URL. However, enrichment figures and weblink to
# STRING website is not available in this version.
#https://version-11-0.string-db.org

[STRING_DB]

functional_enrichment=TRUE
webLink = TRUE
description = TRUE
enrichment_image=TRUE

network_image=TRUE
# Available output formats
# image / highres_image / svg
imagetype= image

[QTL]
# Search eQTL information
eQTL = FALSE

# Search eQTL information (works on GRCh38)
sQTL = FALSE

# dataset Id for GTEx Portal
# https://gtexportal.org/home/releaseInfoPage
dataset = gtex_v10

# FDR p-value threshold for filtering the eQTL results.
pvalue_threshold = 5E-5

[graphs]
# Present output as graphs in addition to Excel reports.
generate_graph = TRUE

# graph layout from igraph package, layout_in_circle , layout_nicely, etc.
layout = layout_nicely

#==============================================
# ================ end of file ================
#==============================================
